language: python
addons:
  firefox: "32.0.3"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies
install:
  - pip install python-coveralls virtualenv
# # command to run tests
script: python setup.py test
after_success:
  - pip install -r requirements-testing.txt -e .
  - py.test --cov=pytest_splinter --cov-report=term-missing tests
  - coveralls
branches:
  except:
    - /^\d/
notifications:
    email:
        - bubenkoff@gmail.com
